[package]
name = "anatris"
version = "0.1.0"
edition = "2021"

[dependencies]
# anathema = { path = "../anathema" }
anathema = { git = "https://github.com/togglebyte/anathema/", branch = "dev" }
rand = "0.8"
smol = "2.0.2"
